r"""d3d.ren unit recovery, step 5: write config/d3dren/units_proposal.md and config/d3dren/WAVE_PLAN.md.

  python tools/d3dren_units_scan.py && python tools/d3dren_units_recover.py && python tools/d3dren_units_wave.py 9
  python tools/d3dren_units_report.py

All numbers in the two documents are recomputed from build/d3dren/units/{scan,units,waves}.json; the prose is in this file.
"""
import bisect
import collections
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
CFG = os.path.join(REPO, 'config', 'd3dren')
OUT = os.path.join(REPO, 'build', 'd3dren', 'units')


def hx(v):
    return '%08x' % v


def load():
    U = json.load(open(os.path.join(OUT, 'units.json')))
    S = json.load(open(os.path.join(OUT, 'scan.json')))
    W = json.load(open(os.path.join(OUT, 'waves.json')))
    ext = json.load(open(os.path.join(OUT, 'units_ext.json')))
    for u in U['units']:
        u.update(ext[u['unit']])
        u['m'] = dict(u['m'])
    return U, S, W


def seed_names():
    """address -> name from the seed sources (// FUNCTION: D3DREN 0xADDR followed by the definition)"""
    names = {}
    for f in glob.glob(os.path.join(REPO, 'src', 'd3dren', 'seed', '*.cpp')):
        lines = open(f, encoding='utf-8', errors='replace').read().split('\n')
        for i, l in enumerate(lines):
            m = re.match(r'\s*//\s*(?:FUNCTION|STUB):\s*D3DREN\s+0x([0-9a-fA-F]{8})\s*(\S*)', l)
            if not m:
                continue
            a = int(m.group(1), 16)
            for k in range(i + 1, min(i + 6, len(lines))):
                t = lines[k].strip()
                if not t or t.startswith('//'):
                    continue
                mm = re.search(r'([~\w:]+)\s*\(', t)
                if mm and a not in names:
                    names[a] = mm.group(1)
                break
    return names


def seed_flag_table(units):
    """flags of the seed sources (src/d3dren/seed/*.cpp) by the kind of region their annotated addresses fall in"""
    starts = [u['lo'] for u in units]
    cnt = collections.defaultdict(collections.Counter)
    for fl in glob.glob(os.path.join(REPO, 'src', 'd3dren', 'seed', '*.cpp')):
        t = open(fl, encoding='utf-8', errors='replace').read()
        m = re.search(r'// FLAGS: (.*)', t)
        flags = m.group(1).strip() if m else '(default /O2)'
        for a in set(re.findall(r'(?:FUNCTION|STUB): D3DREN 0x(1[0-9a-fA-F]{7})', t)):
            a = int(a, 16)
            i = bisect.bisect_right(starts, a) - 1
            if i >= 0 and units[i]['lo'] <= a < units[i]['hi'] and units[i]['kind'] in 'AP':
                cnt[units[i]['kind']][flags] += 1
    return cnt


def md_table(rows, header):
    out = ['| ' + ' | '.join(header) + ' |', '|' + '|'.join('---' for _ in header) + '|']
    for r in rows:
        out.append('| ' + ' | '.join(str(c) for c in r) + ' |')
    return '\n'.join(out)


# =========================================================================================================== proposal
def write_proposal(U, S, W):
    units = U['units']
    src = [u for u in units if u['src']]
    by = collections.Counter()
    nf = collections.Counter()
    for u in units:
        by[u['conf']] += u['hi'] - u['lo']
        nf[u['conf']] += u['m']['nf']
    total_text = U['text'][1] - U['text'][0]
    unit_bytes = sum(u['hi'] - u['lo'] for u in units)
    ren_bytes = sum(u['hi'] - u['lo'] for u in src)
    lib_bytes = U['lib_bytes']
    pad_bytes = sum(b - a for a, b, p in U['uncovered'])
    A = [u for u in src if u['kind'] == 'A']
    P = [u for u in src if u['kind'] == 'P']
    L = []
    w = L.append
    w('# d3d.ren source-unit recovery (proposal)')
    w('')
    w('Generated by `tools/d3dren_units_scan.py`, `d3dren_units_regions.py`, `d3dren_units_recover.py`, `d3dren_units_wave.py` and `d3dren_units_report.py` '
      '(re-runnable; `d3dren_units_experiments.py` reproduces the validation numbers).  Module: `E:\\AVP2Source\\bin\\talon\\d3d.ren` '
      '(DirectDraw 7 / Direct3D 7 renderer of LithTech 2.2 "Talon"), `.text` 0x10001000-0x10045890.  There are no function names yet, so unlike the '
      'lithtech.exe proposal the evidence is structural (alignment and padding, data pool order, flags, static initialisers), not names.')
    w('')
    w('## Result')
    w('')
    w('* **%d units** in `units.csv`: %d renderer source units (%d aligned A runs, %d packed P regions), 3 prebuilt StdLith library objects found at '
      'the end of the renderer region, 2 import-library thunk blocks.' % (len(units), len(src), len(A), len(P)))
    w('* `.text` accounting (%d bytes = 0x%x): renderer source **%d bytes (%.1f%%)**, prebuilt StdLith objects %d bytes, import thunks %d bytes, '
      'libraries.json CRT code %d bytes (%.1f%%), CRT alignment padding between library sections %d bytes (%d gaps, all 0xCC), **unassigned 0**.' % (
          total_text, total_text, ren_bytes, 100.0 * ren_bytes / total_text,
          sum(u['hi'] - u['lo'] for u in units if u['kind'] == 'L'), sum(u['hi'] - u['lo'] for u in units if u['kind'] == 'I'),
          lib_bytes, 100.0 * lib_bytes / total_text, pad_bytes, len(U['uncovered'])))
    w('* Functions: %d renderer functions in %d source units (1,269 in the renderer region of FACTS.md; the 13 StdLith/thunk-area functions belong to the library units).' % (
        sum(u['m']['nf'] for u in src), len(src)))
    w('')
    rows = []
    for c in ('high', 'medium', 'low'):
        us = [u for u in units if u['conf'] == c]
        rows.append((c, len(us), '%d (0x%x)' % (by[c], by[c]), '%.1f%%' % (100.0 * by[c] / unit_bytes), nf[c]))
    w(md_table(rows, ['confidence', 'units', 'bytes', '% of unit bytes', 'functions']))
    w('')
    w('What the confidence means: it is the confidence that `[start,end)` is exactly **one original object file**.  Every boundary listed is exact (hard '
      'evidence, below); what is uncertain is whether an A run holds one object or several, and the unit names.')
    w('* **high** (%d units): P regions (one packed `.text` section, proven by padding), library objects (byte match), import thunks.' % sum(1 for u in units if u['conf'] == 'high'))
    w('* **medium** (%d units): A runs that are small enough to be one object (<= 10 KB) or whose private `.bss` variables are in hash order '
      '(a single C++ object; several objects would put them in link order).' % sum(1 for u in units if u['conf'] == 'medium'))
    w('* **low** (%d units): A runs above 10 KB with `.bss` order that is compatible with several objects: `%s`.  Treat each as one work unit '
      '(merging objects into one translation unit is harmless for byte matching; cutting an object in two is not).' % (
          sum(1 for u in units if u['conf'] == 'low'), '`, `'.join(u['unit'] for u in units if u['conf'] == 'low')))
    w('')
    w('## Method')
    w('')
    w('1. **Library exclusion.** `libraries.json` places 238 CRT sections (41,054 bytes) after the renderer; the build owner already dropped the two false '
      '`_srand`/`_localeconv` placements at 0x100099a9/0x100099b3 (a getter/setter pair for `DAT_100528d8` between two ConVar initialisers); '
      '`d3dren_units_scan.py` also ignores them if they come back.  Everything below 0x1003b710 is renderer or non-CRT library code.')
    w('2. **Alignment / padding structure** (the one hard signal; `d3dren_units_regions.py`).  Two kinds of objects exist, and they alternate:')
    w('   * **A runs**: every function starts and ends 16-aligned, padded with 0x90 (COMDAT functions, `/O2` implies `/Gy`).  %d runs, %d bytes, %d functions.' % (
        len(A), sum(u['hi'] - u['lo'] for u in A), sum(u['m']['nf'] for u in A)))
    w('   * **P regions**: functions follow each other without padding (one plain `.text` section per object); the section starts 16-aligned and the '
      'linker pads its end with 0xCC.  %d regions, %d bytes, %d functions.  All 12 P regions start 16-aligned (probability 4^-12 if the section '
      'alignment were 4), 11 of the 12 P regions end with a 0xCC pad before an A run (the last one ends at the DDRAW import thunks), and **no 0xCC pad occurs inside a P region**: a P->P boundary would '
      'show one with probability 15/16, so a P region is one object.  Inside the P regions %d of %d function ends are 16-aligned without padding, '
      '%.0f expected by chance (1 in 16): no excess, so none of them needs to be an exactly aligned object boundary.' % (
          len(P), sum(u['hi'] - u['lo'] for u in P), sum(u['m']['nf'] for u in P), U['facts']['p_aligned_ends'], U['facts']['p_boundaries'], U['facts']['p_expected']))
    w('   * The switch between A and P is an object boundary (an object is all-/Gy or not), and the object kind gives its compile flags: the seed '
      'sources of the build owner (`src/d3dren/seed/*.cpp`, byte-matched functions) were compiled `/O2 /Ob2` for every address in an A run and `/O1 /Ob2` '
      'for every address in a P region (table below).  So **units differ in flags and need a per-unit `// FLAGS:` line**.')
    f = U['facts']
    w('3. **Layout evidence that the order along the address space is the link order** (all consistent, none contradicted): the `.CRT$XCU` table (0x10048004..) lists %d '
      'static-initialiser wrappers in strictly ascending address order; the %d `.data` string literals (/Gf pool, 0x100483a0-0x1004c214) are in ascending order of the address '
      'of their first user (%d inversions between consecutive strings); the %d referenced `.rdata` items (`__real@` float COMDATs, vtables, switch tables, '
      '0x10046140-0x10046664) likewise (%d inversion).  So the first user of a constant or string identifies the owning object, and the pools give the *order* of objects '
      'but, because the items of an object are contiguous without a separator, no boundary by themselves.' % (
          f['xcu'], f['strings'], f['str_inv'], f['rdata'], f['rdata_inv']))
    w('4. **Library objects not in libraries.json.** The last A run (0x1003b520-0x1003b710) is prebuilt StdLith code, byte-identical outside relocations to '
      '`libs_objs\\LT_StdLith\\struct_bank.obj` (`sb_Init`, `sb_Init2`, `sb_Term2`, `sb_Term`, `sb_AllocateNewStructPage`), `l_allocator.obj` (`LAlloc::Alloc/Free`, '
      '`??_GLAlloc`, the `g_DefAlloc` static initialiser group) and `dynarray.obj` (`MoArray_FindElementMemcmp`).  The unreferenced sections of these objects were '
      'removed by /OPT:REF.  libmatch skips the lithshared libraries, hence FACTS.md\'s "no StdLith code found".  **The seed STUB for 0x1003b5f0 '
      '(`src/d3dren/seed/pool_grow.cpp`, 12 instructions "register choice" mismatch) is `sb_AllocateNewStructPage` of a prebuilt object: it cannot be matched from source '
      'with this compiler and does not need to be.**  Add the three objects to `libraries.json`.')
    w('5. **Import thunks**: `0x1003b502-0x1003b520` (DirectDrawCreate, DirectDrawCreateEx, DirectDrawEnumerateA: `jmp [iat]`) and `0x10045880-0x10045890` '
      '(`RtlUnwind`) are Import0 objects; they are units `imp/...` so that the partition has no hole, but they are not source.')
    w('6. **Names**: only where a distinctive Jupiter file match exists (`sys/d3d/<base>`, strength given in the evidence column); otherwise `unk/<hex of the first function>`.  '
      'The Jupiter renderer is DX9 and was largely rewritten, so only strings, ConVar names and the allocator/ConVar helpers overlap '
      '(`common_stuff.cpp`, `tagnodes.cpp`, `d3d_init.cpp`, `d3d_surface.cpp`, `d3d_texture.cpp`).')
    w('')
    w('### Flag evidence (seed sources of the build owner, byte-matched functions)')
    w('')
    cnt = seed_flag_table(units)
    rows = []
    for kind in ('A', 'P'):
        for flags, n in sorted(cnt[kind].items(), key=lambda x: -x[1]):
            rows.append(({'A': 'A run (16-aligned COMDATs)', 'P': 'P region (packed)'}[kind], '`%s`' % flags, n))
    w(md_table(rows, ['region kind', '`// FLAGS:` of the seed file', 'annotated functions']))
    w('')
    w('(The two `/O2` annotations in P regions are `matops2.cpp` (a provisional seed grouping flagged `/O2`) at 0x1000832e (`unk/10007930`) and 0x1000dd34 (`unk/100098d0`): '
      'either mis-flagged in the seed or not matched yet; every other annotated function agrees with the A/P rule.  `matops2.cpp` also holds 0x100098b0, the last function of the A run before `unk/100098d0`.)')
    w('')
    w('## Units')
    w('')
    rows = []
    for u in units:
        m = u['m']
        rows.append(('`%s`' % u['unit'], '%s-%s' % (hx(u['lo']), hx(u['hi'])), '%d' % (u['hi'] - u['lo']), m['nf'], u['conf'],
                     {'A': 'A /O2', 'P': 'P /O1', 'L': 'lib', 'I': 'imp'}[u['kind']],
                     u['lang'].split(' (')[0] if u['kind'] in 'AP' else '-'))
    w(md_table(rows, ['unit', 'range', 'bytes', 'functions', 'confidence', 'kind/flags', 'language']))
    w('')
    w('Language: `C++` when the unit has static initialisers (`_$E`), vtables or `new`/`delete` calls; `C?` otherwise.  Only `unk/10007930` has no C++ marker, so the '
      '~32 renderer C objects of the Rich header (FACTS.md section 3) are mostly *not* visible as units of their own: they sit inside A runs (small `/Gy` objects '
      'without static initialisers or vtables have no signature).')
    w('')
    w('### Evidence per unit')
    w('')
    for u in units:
        w('* `%s` %s-%s (%s): %s' % (u['unit'], hx(u['lo']), hx(u['hi']), u['conf'], ' | '.join(u['evidence'])))
    w('')
    import d3dren_units_regions as RG
    tb, tlo = RG.text_bytes()
    byend = {f['end']: f for f in S['funcs']}
    w('## Boundaries and their confidence')
    w('')
    rows = []
    srcu = [u for u in units]
    for a, b in zip(srcu, srcu[1:]):
        if a['hi'] != b['lo']:
            continue
        f = byend.get(a['hi'])
        pt, pn = RG.pad_info(f, tb, tlo) if f else ('x', 0)
        if a['kind'] == 'A' and b['kind'] == 'P':
            ev = 'A->P: last A function padded with %d x 0x90 to the 16-aligned start of a packed section (hard)' % pn if pn else 'A->P: A function ends exactly aligned, next function is a packed one (hard)'
        elif a['kind'] == 'P' and b['kind'] == 'A':
            ev = 'P->A: packed section padded with %d x 0xCC to the first aligned COMDAT (hard)' % pn if pt == 'c' else 'P->A (hard)'
        elif b['kind'] == 'I':
            ev = 'end of the P region; DDRAW import thunks follow (hard)'
        elif a['kind'] == 'I' or a['kind'] == 'P' and b['kind'] == 'L':
            ev = 'import thunks / library object start (byte match, hard)'
        elif a['kind'] == 'L' and b['kind'] == 'L':
            ev = 'library object boundary: end of the last matched section of %s (byte match)' % a['unit']
        else:
            ev = '-'
        rows.append((hx(a['hi']), '`%s` -> `%s`' % (a['unit'], b['unit']), 'high', ev))
    w(md_table(rows, ['address', 'units', 'confidence', 'evidence']))
    w('')
    w('All %d boundaries between consecutive units are hard (exact addresses); the only soft element is whether an A run contains further, invisible, object starts (the unit confidence '
      'column, and the candidate cut points below).' % len(rows))
    w('')
    w('## Link order')
    w('')
    w('Alphabetical by object base name (as in the lithtech.exe module)?  **Consistent, not proven.**  The five names with a distinctive Jupiter match come out in '
      'alphabetical order along the address space: `common_stuff` (0x1000f3a0) < `d3d_init` (0x10019b10) < `d3d_surface` (0x1001bf10) < `d3d_texture` (0x1001e5a0) < '
      '`drawpolygrid` (0x1002afd0) < `tagnodes` (0x10038830).  Jupiter itself is no oracle: `Lithtech.map` links the D3DRender code as a library in pull order '
      '(`ltvertexshadermgr, lteffectshadermgr, ltpixelshadermgr, rendererframestats, common_stuff, ...`), not alphabetically, and `lib_d3drender.pdb` is the VS2010 '
      'DX9 renderer (no Talon objects).  The first renderer objects (the ConVar-heavy A/P pairs before `common_stuff`) would have to sort before `common_stuff`; '
      'they hold model/vertex-buffer/clip code, so names like `3d_ops`, `aabb`, `common_draw` fit alphabetically but nothing ties them to those regions.')
    w('')
    w('## What did not work (and why units are whole runs, not cut finer)')
    w('')
    w('`d3dren_units_experiments.py` tests structural signals for object boundaries *inside* A runs against the 24 hard boundaries:')
    w('* call coupling between the 8 functions before/after a position: hard boundaries are in the lowest 20% of the score only for 58% of positions (random: 20%); '
      'shared private data between the windows: 25-38%.  Too weak to cut with.')
    w('* modularity-style DP on call+shared-data edges, min-cut DP and a windowed `.bss` seriation were tried (scratch scripts, not kept): they either never split or split '
      'inside ConVar `_$E` blocks (hash-ordered, edge-free singletons).')
    w('* `.bss` order is a *merge* signal only: extern globals of one C++ object are in name-hash order (rho ~ 0: `unk/10001000` -0.01 over 20 variables, '
      '`unk/100132a0` -0.13 over 142, `sys/d3d/tagnodes` -0.07 over 45, `common_stuff` +0.06 over 737), several objects would be in link order (rho > 0).  File-statics are '
      'in definition order (rho > 0 even for a single object, e.g. P regions up to +1.00), so a positive rho proves nothing.  In particular `unk/100098d0` has two '
      'ConVar blocks in disjoint `.bss` ranges (rho +0.66) although it is one object by the padding argument.')
    w('* The Rich header counts ~97 renderer objects (about 30 C, 67 C++); this analysis finds **%d code regions** (12 proven single objects) plus 3 StdLith objects.  '
      'Either many objects are tiny `/O2` objects inside the A runs (invisible), or many contribute no `.text`.  This is the main open question.' % len(src))
    w('')
    w('## Candidate internal cut points (not applied)')
    w('')
    na = sum(1 for u in units if u.get('starts_init') and u['kind'] == 'A')
    nA = sum(1 for u in units if u['kind'] == 'A' and u['src'])
    npp = sum(1 for u in units if u.get('starts_init') and u['kind'] == 'P')
    nP = sum(1 for u in units if u['kind'] == 'P' and u['src'])
    w('For the A runs (an object start cannot be proven there) two weak signals are reported.  Interior static-initialiser blocks: %d of the %d A runs and %d of the %d P regions '
      'start with their static initialisers (globals and ConVars are defined first), so an XCU block far from the start of a run is a candidate object start (about %d%% base rate, '
      'the rest are mid-file definitions).  Coupling minima are listed only for the `low` runs.' % (na, nA, npp, nP, round(100.0 * (na + npp) / (nA + nP))))
    w('')
    rows = []
    for u in units:
        if u.get('kind') != 'A':
            continue
        ib = ', '.join('%s (%d `_$E`)' % (hx(a), n) for a, n in u.get('init_blocks', []))
        cuts = ', '.join('%s (coupling %g)' % (hx(a), c) for c, a in u.get('cuts', []))
        if ib or cuts:
            rows.append(('`%s`' % u['unit'], u['conf'], ib or '-', cuts or '-'))
    w(md_table(rows, ['unit', 'confidence', 'interior static-init blocks', 'coupling minima']))
    w('')
    w('Best candidates: `0x1001a380` (4 ConVars UseD3DClip/MipMapBias/Trilinear/Anisotropic, after the single 0x870-byte DDERR/D3DERR text-table function at the top of `sys/d3d/d3d_init`; '
      'Jupiter puts the text tables and ForceMode in d3d_device.cpp and LISTDEVICECAPS in d3d_init.cpp, d3d_device < d3d_init alphabetically), `0x1002f330` (the `DrawWorldModels` ConVar '
      'block in `unk/1002d080`, which also starts with the `AllSkyPortals` block) and `0x1002d640`.')
    w('')
    w('## Open questions / decisions for the build owner')
    w('')
    w('1. `config/d3dren/units.csv` previously held one seed row `render/polyclip,10001a50,10001b30,low`; it is superseded by `unk/10001000` (0x10001a50 and 0x10001ac0 are inside '
      'the A run 0x10001000-0x10007930).  The seed sources keep their `// FUNCTION:` annotations, but their unit names (`src/d3dren/seed/...`) are not units any more; '
      'decide whether the seeds are re-homed into the unit files or the units get `seed` aliases.')
    w('2. Add `lib/LT_StdLith/struct_bank`, `l_allocator`, `dynarray` (0x1003b520-0x1003b710) to `libraries.json`; they are byte-identical to `libs_objs\\LT_StdLith`.  '
      'Until then they are `lib/...` rows with confidence high in `units.csv`, and `imp/*` rows are thunks, not source: `build.py` must not try to compile them.')
    w('3. Per-unit flags: A runs `/O2 /Ob2`, P regions `/O1 /Ob2` (seed evidence).  `FACTS.md` section 5 is still empty; this table can fill it.')
    w('4. The object-count gap (97 vs %d regions), see above.  If the objects inside the large A runs matter for relinking, the data (`.rdata`/`.data`/`.bss`) '
      'gates will show the real boundaries later (string pool and `__real@` order per object); until then the units are unions of whole objects.' % len(src))
    w('')
    open(os.path.join(CFG, 'units_proposal.md'), 'w', encoding='utf-8', newline='\n').write('\n'.join(L) + '\n')


# =========================================================================================================== wave plan
def write_wave(U, S, W):
    units = U['units']
    byname = {u['unit']: u for u in units}
    funcs = S['funcs']
    names = seed_names()
    starts = [u['lo'] for u in units]

    def uidx(a):
        i = bisect.bisect_right(starts, a) - 1
        return i if i >= 0 and units[i]['lo'] <= a < units[i]['hi'] else None

    # call matrix, fan-in per function
    M = collections.Counter()
    fanin = collections.defaultdict(set)
    for f in funcs:
        i = uidx(f['addr'])
        if i is None:
            continue
        for c in f['calls']:
            j = uidx(c)
            if j is not None and j != i:
                M[(i, j)] += 1
                fanin[c].add(i)
    pk_of = {}
    for p in W['packages']:
        for un in p['units']:
            pk_of[un] = p['id']
    # shared globals (>= 4 units)
    gu = collections.defaultdict(collections.Counter)
    for f in funcs:
        i = uidx(f['addr'])
        if i is None or not units[i]['src']:
            continue
        for v in f['drefs'] + f['brefs']:
            if v >= 0x1004d5a0:
                gu[v][units[i]['unit']] += 1
    gnames = {}
    for fl in glob.glob(os.path.join(REPO, 'src', 'd3dren', 'seed', '*.cpp')) + glob.glob(os.path.join(REPO, 'include', 'd3dren', '*.h')):
        lines = open(fl, encoding='utf-8', errors='replace').read().split('\n')
        for k, l in enumerate(lines):
            m = re.match(r'\s*//\s*GLOBAL:\s*D3DREN\s+0x([0-9a-fA-F]{8})', l)
            if m and k + 1 < len(lines):
                mm = re.search(r'([A-Za-z_]\w*)\s*(?:\(|;|=|\[)', lines[k + 1].replace('extern', ''))
                if mm:
                    gnames[int(m.group(1), 16)] = mm.group(1)
    K = W['K']
    pk = W['packages']
    tb = sum(p['bytes'] for p in pk)
    tf = sum(p['nf'] for p in pk)
    tn = sum(p['nontrivial'] for p in pk)
    L = []
    w = L.append
    w('# d3d.ren decompilation: work packages (wave plan)')
    w('')
    w('Generated by `tools/d3dren_units_wave.py` / `d3dren_units_report.py` from `config/d3dren/units.csv` (see `units_proposal.md` for what a unit is).  '
      'The partition is reproducible (fixed random seeds).')
    w('')
    w('## Overview')
    w('')
    w('* Scope: the **%d renderer source units** (%d bytes, %d functions); the 3 StdLith library objects and the import thunks are not decompiled '
      '(byte-identical prebuilt code, see `units_proposal.md`).' % (sum(1 for u in units if u['src']), tb, tf))
    w('* **%d packages**, disjoint, each owning whole units.  Balanced metrics: **code bytes and non-trivial functions** (a non-trivial function is one that is not a '
      'static-initialiser wrapper/body (`_$E` groups: ~300 ConVar definitions are copy-paste work) or a 1-byte `ret` stub: %d of %d).  The plain function count is '
      'reported as well; it cannot be balanced further because `common_stuff` alone holds 237 functions (about 190 of them ConVar initialisers) and `unk/100098d0` 175.' % (K, tn, tf))
    w('* Result: bytes %d-%d%% of the mean (%d), non-trivial functions %d-%d%% of the mean (%d), plain function count %d-%d%% of the mean (%d).  '
      'The spread is limited by indivisible units: the largest (`unk/10001000`, 0x6930 bytes) is %d%% of the mean package.' % (
          min(100 * p['bytes'] * K // tb for p in pk), max(100 * p['bytes'] * K // tb for p in pk), tb // K,
          min(100 * p['nontrivial'] * K // tn for p in pk), max(100 * p['nontrivial'] * K // tn for p in pk), tn // K,
          min(100 * p['nf'] * K // tf for p in pk), max(100 * p['nf'] * K // tf for p in pk), tf // K,
          100 * 0x6930 * K // tb))
    w('')
    rows = []
    for p in pk:
        rows.append((p['id'], ', '.join('`%s`' % u for u in p['units']), p['bytes'], '%d%%' % (100 * p['bytes'] * K // tb), p['nf'], p['nontrivial'],
                     '%d%%' % (100 * p['nontrivial'] * K // tn), p['x87'], p['com'], p['switches']))
    w(md_table(rows, ['package', 'units', 'bytes', 'of mean', 'functions', 'non-trivial', 'of mean', 'x87 insns', 'virtual calls', 'switch tables']))
    w('')
    w('Dependencies between packages are heavy (every unit calls `common_stuff`, the Direct3D7 state wrappers of `unk/100098d0` and the vertex-buffer code of `unk/10001000`; '
      'only a small fraction of the cross-unit call edges stay inside a package), so the plan is organised around **shared headers that must exist first** (below), not around call locality.  '
      'Order of work in time: the foundation packages publish their headers first (the seeds already hold most of them): %s; then all packages run in parallel.' %
      '; '.join('%s `%s`' % (pk_of[u], h) for u, h in (('sys/d3d/common_stuff', 'common_stuff.h/rendererconsolevars.h'), ('sys/d3d/d3d_init', 'd3ddevice.h'),
                                                    ('unk/100098d0', 'd3dstate.h'), ('unk/10001000', 'tlvertex.h/vbpool.h/viewparams.h'),
                                                    ('sys/d3d/d3d_texture', 'd3dtexture.h'))))
    w('')
    w('## Toolchain and flags (read before touching a unit)')
    w('')
    w('* Compiler: **VC6 SP5 front ends + the SP5 optimising back end C2 12.0.8966** (`tools/vc6cl_d3dren.bat`; build owner\'s note: `ClipLineZ` 0x10001a50 byte-matches, '
      'including the x87 compare sequences).  The original Rich header says C2 build 8168 (RTM), so rare residual codegen differences from the RTM back end are possible.  '
      'd3d.ren is DirectDraw 7 / Direct3D 7 (DX 8.0 SDK headers with `DIRECTDRAW_VERSION`/`DIRECT3D_VERSION` 0x0700).  115 renderer functions / 107 KB contain x87 compares: '
      'a statistic, not a blocker.')
    w('* **Flags differ per unit**: A runs (16-aligned COMDATs) were built `/O2 /Ob2`, P regions (packed, no padding) `/O1 /Ob2` (size optimisation: `fldz/fstp` for 0.0f, '
      '`and [m],0`, ebp frames, `sahf` compares).  Put `// FLAGS: /O1 /Ob2` (P) or `// FLAGS: /O2 /Ob2` (A) at the top of every unit; the build default is `/O2`.')
    w('* No exception handling (`/GX` off, no `.xdata`), but `__purecall` is linked: abstract classes exist.  C++ static initialisers follow the lithtech rules (`_$E` wrapper/body '
      'groups numbered per object; the numbers of one object continue through its ConVar blocks, e.g. `_$E146+` in `common_stuff`): keep a unit\'s ConVar blocks in one source file in address order.')
    w('* Inline-budget traps (see README "How VC6 decides what to inline"): `/Ob2` here, so calls to SDK inlines (`LTMatrix`/`LTVector` members), `CMoArray` accessors and '
      'the ConVar constructor (inlined into ~100 initialisers of `common_stuff`, called out of line from the A-run objects) behave like the exe: reproduce the out-of-line copies '
      'with the STANDIN technique (the seeds `matops.cpp`, `vecops.cpp` do).  The ConVar constructor 0x100111b5 is **out of line** in the A runs and **inlined** in the P regions.')
    nhuge = sum(u.get('huge', 0) for u in units if u['src'])
    nx87 = sum(u['x87funcs'] for u in units if u['src'])
    w('* x87 code: %d non-trivial functions use the x87 FPU, %d of them with compares (build owner: 115 / 107 KB in the whole image); %d functions are larger than 0x800 bytes (per-package risk lines).  '
      'Statement order and `(float)` casts matter; use the lithtech README "Floating point" notes.' % (nx87, sum(u['x87cmp'] for u in units if u['src']), nhuge))
    w('')
    w('## Shared headers (define once, in `include/d3dren/`)')
    w('')
    gtop = sorted(gu.items(), key=lambda x: -len(x[1]))
    hot = []
    for v, c in gtop[:14]:
        hot.append(('`%s`' % hx(v), gnames.get(v, '-'), len(c), sum(c.values()), ', '.join('%s %d' % (k.split('/')[-1], n) for k, n in c.most_common(3))))
    hdr = [
        ('`common_stuff.h`', 'exists (seed)', '`sys/d3d/common_stuff`', 'g_pStruct (RenderStruct*), dalloc/dalloc_z/dfree (0x10012ce5/cfe/d44), console print, ConVar creation; used by every unit'),
        ('`rendererconsolevars.h`', 'exists (seed)', '`sys/d3d/common_stuff`', 'ConVar class (ctor 0x100111b5) and every `g_CV_*` extern + cached `DAT_` ints (0x10048720-0x10048788, 0x10057xxx-0x10058xxx); declare the A-run ConVars (model, NearZ, VFog.., Trilinear.., Sort.., Portal..) here too'),
        ('`tlvertex.h`, `vertfill.h`, `fixedpoint.h`, `vbpool.h`, `pool.h`', 'exist (seed)', '`unk/10001000` (pool.h: `unk/10007930`)', 'TL vertex (0x20 bytes), vertex fillers, clipper, the 4 vertex-buffer pool objects and their base class (`unk/1003a680`), node pool'),
        ('`modeldraw.h`', 'exists (seed)', '`unk/10001000`', 'model drawer callbacks (0x10004230..), used by `unk/100098d0`, `unk/100241e0`'),
        ('`d3ddevice.h`', 'NEW', '`sys/d3d/d3d_init`', 'the DirectDraw7/Direct3D7 globals (`IDirect3DDevice7*` 0x1005de30 with 115 users in 16 units, 0x1005de28, device caps and the texture-format table around 0x10058470), device creation, DDERR/D3DERR text (0x10019b10)'),
        ('`d3dstate.h`', 'NEW (seed `d3dstate.cpp`)', '`unk/100098d0`', 'texture binding and render-state set/restore wrappers 0x10009ea5-0x1000a521, used by every drawing unit'),
        ('`viewparams.h`', 'NEW', '`unk/10001000`', 'view/clip globals: near plane 0x10055d80/0x10055d88, the 16-float block 0x10055e94-0x10055ed0, scratch vertex buffers 0x1005627c/0x1005668c, frame counters 0x1005626c'),
        ('`d3dtexture.h`', 'NEW', '`sys/d3d/d3d_texture`', 'texture/surface structs and the format table ([LIGHTMAP][INTERFACE][NORMAL][4444][FULLBRITE]), upload; used by `d3d_surface`, `drawpolygrid`, `unk/10034000`, `unk/10029660`'),
        ('`lightmap.h`', 'NEW', '`unk/10034000`', 'lightmap pages and LightAnim (used by `unk/100329b0`, `unk/10030bb0`, the world draw units)'),
        ('`drawpolymgr.h`', 'NEW', '`unk/10029660`', 'DrawPolyMgr (state-block based multi-pass polygon drawing)'),
        ('`visibleset.h`', 'NEW', '`sys/d3d/tagnodes`', 'VisibleSet and the VS_* object lists; `VisibleSet::Init` is called by the init code in `common_stuff`'),
        ('`ltdynarray.h` (engine, exists)', 'exists in `include/`', 'engine', 'CMoArray template instances (vtables 0x100463ec, 0x1004641c, 0x100464ec...) in `unk/100285a0`, `unk/1003a680`, `sys/d3d/tagnodes`'),
    ]
    def own(cell):
        mm = re.findall(r'`([^`]+)`', cell)
        ids = sorted(set(pk_of[x] for x in mm if x in pk_of))
        return cell + (' (%s)' % ', '.join(ids) if ids else '')
    w(md_table([(h, st, own(o), c) for h, st, o, c in hdr], ['header', 'status', 'owner unit (package)', 'content / evidence']))
    w('')
    w('Rule (as for the engine): extend an existing header with small targeted edits, never clobber another package\'s header; check `grep -rn "class X\\|struct X" include` first.')
    w('')
    w('Most widely shared data (referenced from >= 4 renderer units; names from the seed headers where they exist):')
    w('')
    w(md_table(hot, ['address', 'seed name', 'units', 'references', 'top users']))
    w('')
    w('## Seed sources (src/d3dren/seed) and the units they belong to')
    w('')
    rows = []
    for fl in sorted(glob.glob(os.path.join(REPO, 'src', 'd3dren', 'seed', '*.cpp'))):
        t = open(fl, encoding='utf-8', errors='replace').read()
        mfl = re.search(r'// FLAGS: (.*)', t)
        us = collections.Counter()
        for a in set(re.findall(r'(?:FUNCTION|STUB): D3DREN 0x(1[0-9a-fA-F]{7})', t)):
            i = uidx(int(a, 16))
            if i is not None:
                us[units[i]['unit']] += 1
        rows.append((os.path.basename(fl), '`%s`' % (mfl.group(1).strip() if mfl else '(default)'), ', '.join('`%s` %d' % (k, n) for k, n in us.most_common()),
                     ', '.join(sorted(set(pk_of.get(k, 'lib') for k in us)))))
    w(md_table(rows, ['seed file', 'flags', 'annotated functions per unit', 'package(s)']))
    w('')
    w('A seed file whose annotated functions span several units is provisional (the seed author grouped by code shape, not by object); move each function into the file of its unit.')
    w('')
    w('## Packages')
    w('')
    # package details
    for p in pk:
        pun = [byname[n] for n in p['units']]
        idxs = [units.index(u) for u in pun]
        out_deps = collections.Counter()
        in_deps = collections.Counter()
        for (i, j), c in M.items():
            pi = pk_of.get(units[i]['unit'])
            pj = pk_of.get(units[j]['unit'])
            if pi == p['id'] and pj and pj != p['id']:
                out_deps[pj] += c
            if pj == p['id'] and pi and pi != p['id']:
                in_deps[pi] += c
        w('### %s: %d bytes, %d functions (%d non-trivial)' % (p['id'], p['bytes'], p['nf'], p['nontrivial']))
        w('')
        rows = []
        for u in pun:
            m = u['m']
            rows.append(('`%s`' % u['unit'], '%s-%s' % (hx(u['lo']), hx(u['hi'])), u['hi'] - u['lo'], m['nf'], u['nontrivial'], u['conf'], 'A /O2 /Ob2' if u['kind'] == 'A' else 'P /O1 /Ob2'))
        w(md_table(rows, ['unit', 'range', 'bytes', 'functions', 'non-trivial', 'confidence', 'flags']))
        w('')
        shape = []
        x87 = sum(u['x87'] for u in pun)
        if x87:
            xf = sum(u['x87funcs'] for u in pun)
            shape.append('x87 float math: %d x87 instructions in %d functions (%d with compares)' % (x87, xf, sum(u['x87cmp'] for u in pun)))
        com = sum(u['com'] for u in pun)
        if com:
            shape.append('%d `call [reg+off]` (Direct3D7/DirectDraw7 COM methods, `RenderStruct` callbacks, C++ virtuals)' % com)
        sw = sum(u['switches'] for u in pun)
        if sw:
            shape.append('%d switch jump tables' % sw)
        vt = sum(u['m'].get('vtables', 0) for u in pun)
        if vt:
            shape.append('%d vtables (classes with virtuals)' % vt)
        cv = sum(u['m'].get('convars', 0) for u in pun)
        if cv:
            shape.append('%d ConVar definitions (static-init pairs: pattern work, one template reproduces them)' % cv)
        w('* How the functions look: ' + '; '.join(shape) + '.')
        w('* Content: ' + ' / '.join('`%s`: %s' % (u['unit'], next((e[9:] for e in u['evidence'] if e.startswith('content: ')), next((e for e in u['evidence'] if e.startswith('name (')), 'see units_proposal.md'))) for u in pun))
        need = []
        for u in pun:
            ui = units.index(u)
            callees = collections.Counter()
            for (i, j), c in M.items():
                if i == ui and units[j]['src'] and pk_of.get(units[j]['unit']) != p['id']:
                    callees[units[j]['unit']] += c
            need.extend(k for k, _ in callees.most_common(3))
        w('* Needs from other packages: ' + (', '.join('%s (%d calls)' % (k, v) for k, v in out_deps.most_common(4)) or 'none') +
          '.  Headers/types: ' + ('`common_stuff.h` + `rendererconsolevars.h`, `d3ddevice.h`' if p['id'] != 'W5' else 'defines `common_stuff.h` + `rendererconsolevars.h`') +
          ', engine types from `include/` (`RenderStruct`, `LTVector`, `LTMatrix`, `LTObject`/world types via `de_objects.h`, `de_world.h`), DDraw7/D3D7 from the DX 8.0 SDK headers (`E:\\AVP2Source\\directx8-msdx8\\include`, version 0x0700).')
        w('* Provides to others: ' + (', '.join('%s (%d calls)' % (k, v) for k, v in in_deps.most_common(4)) or 'none') + '.')
        # hot functions
        hotf = []
        for u in pun:
            for f in funcs:
                if u['lo'] <= f['addr'] < u['hi'] and len(fanin.get(f['addr'], ())) >= 3:
                    hotf.append((len(fanin[f['addr']]), f['addr'], f['end'] - f['addr']))
        hotf.sort(reverse=True)
        if hotf:
            w('* Hot shared functions (called from >= 3 other units): ' + ', '.join('`%s`%s (%d units, %d bytes)' % (hx(a), ' ' + names[a] if a in names else '', n, sz) for n, a, sz in hotf[:6]) + '.')
        # order
        order = sorted(pun, key=lambda u: (u['hi'] - u['lo']) + 8 * u['x87funcs'])
        w('* Order: ' + ' -> '.join('`%s`' % u['unit'] for u in order) + ' (smallest/least x87 first); inside a unit: static-initialiser/ConVar blocks first (template work), '
          'then leaf functions (no calls, < 0x60 bytes), then the middle, the giant functions last.')
        risks = []
        for u in pun:
            for a, sz, nfp, ncom in u['top'][:2]:
                if sz >= 0x400:
                    risks.append('`%s` 0x%x bytes%s%s' % (hx(a), sz, ', %d x87 insns' % nfp if nfp else '', ', %d virtual calls' % ncom if ncom else ''))
        rk = []
        if risks:
            rk.append('huge functions: ' + '; '.join(risks[:5]))
        xc = sum(u['x87cmp'] for u in pun)
        if xc:
            rk.append('%d functions with x87 compares (compare/branch shape must come out as the original: SP5 C2 12.0.8966 reproduces it, residual 8168 differences possible)' % xc)
        if any(u['kind'] == 'P' for u in pun):
            rk.append('P units are `/O1`: ebp frames and size-optimised idioms, `/Ob2` inlining decisions (SDK inline copies emitted out of line need STANDIN carriers)')
        if any(u['kind'] == 'A' for u in pun):
            rk.append('A units may hold several objects (confidence column): keep function order = address order, do not reorder across suspected object starts')
        rk.append('no EH, no SEH: nothing to emulate')
        w('* Risks: ' + '; '.join(rk) + '.')
        w('')
    w('## What a fresh agent does first')
    w('')
    w('1. Read `config/d3dren/units_proposal.md` (method, what a unit is, the A/P flags rule) and this file; `python tools/pedis.py --module d3dren <hexVA>[:len]` disassembles, '
      '`E:\\AVP2Source\\out\\decomp\\d3d_ren_v2.c` has the Ghidra C of every function (grep `// ==== <addr>`).')
    w('2. Take your package from the table; for each unit create `src/d3dren/<unit>.cpp` (unit `sys/d3d/d3d_texture` -> `src/d3dren/sys/d3d/d3d_texture.cpp`, `unk/10001000` -> '
      '`src/d3dren/unk/10001000.cpp`) with `// FLAGS: /O2 /Ob2` (A) or `/O1 /Ob2` (P) in the first 30 lines.  Check `src/d3dren/seed/` and `include/d3dren/` first: the seed '
      'files already cover the ConVar blocks, the model vertex fillers, the polygon clipper (0x10001530-0x10007670), the node pool and the TL vertex types; move them into the unit file '
      'rather than rewriting (keep their `// FUNCTION:` annotations).')
    w('3. Order inside the package as listed; do the static-initialiser/ConVar blocks first (they fix the `_$E` numbering and the `.data`/`.bss` layout for the rest of the unit), '
      'then leaves, then the big functions.  Annotate with `// FUNCTION: D3DREN 0x<addr>`; STUB until it matches.')
    w('4. Shared headers: if a header you need is listed above as owned by another package, wait for it only if it is NEW and your unit would otherwise have to guess a layout; '
      'put a minimal declaration (offset-asserted members with `uint8 m_PadXX[]`) in the owner\'s header, small edit, and tell the owner.  Never define the same struct in two places.')
    w('5. Do not decompile the 0x1003b520-0x1003b710 StdLith objects or the CRT; they are prebuilt (`lib/...` units).  `0x1003b5f0` is NOT a STUB to finish.')
    w('6. Raise any boundary doubt (a function that clearly belongs to the neighbouring unit: string pool order, static-init group, a callee that is file-static) in your report instead of '
      'moving it; the unit map is a proposal.')
    w('')
    open(os.path.join(CFG, 'WAVE_PLAN.md'), 'w', encoding='utf-8', newline='\n').write('\n'.join(L) + '\n')


def main():
    U, S, W = load()
    write_proposal(U, S, W)
    write_wave(U, S, W)
    print('wrote units_proposal.md and WAVE_PLAN.md')


if __name__ == '__main__':
    main()
