"""PARKED.md: the parked STUBs (build.py parked [-a]; -a lists every STUB).

A STUB is parked when no known lever is left: its remaining difference is explained (the behaviour audit shows
no difference, or only inlining decisions) and every README rule and tool has been tried on it. Its comment block
(directly above the `// STUB:` line) carries `// PARKED: <reason>`; remove that line to unpark it. Parked
functions stay in the build and are still checked and diffed; agents skip them until a new rule or tool arrives.
"""
import os, subprocess, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'PARKED.md')


def _md(t):
    return t.replace('|', '\\|')


def write(results, objs, exe, symtab, audits, aligned_counts, all_stubs=False):
    rows = []
    for r in results:
        a = r.a
        if a.kind != 'STUB' or not (a.parked or all_stubs) or a.symbol is None:
            continue
        o = objs.get(a.unit.name)
        n, ns, li, ri = aligned_counts(r, o, exe) if o is not None else (None, None, 0, 0)
        ext = symtab.funcs.get(a.va)
        rows.append(dict(a=a, r=r, n=n, ns=ns, li=li, ri=ri, exe=(ext[0] - a.va) if ext else None,
                         audit=audits.get(a.va, '?')))
    rows.sort(key=lambda x: (x['ns'] if x['ns'] is not None else 10 ** 9, x['a'].va))
    try:
        head = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], cwd=ROOT, capture_output=True,
                              text=True).stdout.strip()
    except Exception:
        head = '?'
    L = ['# Parked functions' if not all_stubs else '# All STUBs', '',
         'Generated by `python tools/build.py parked%s` at commit %s, %s. Do not edit by hand.' % (
             ' -a' if all_stubs else '', head, time.strftime('%Y-%m-%d')),
         '',
         'A parked function is a STUB with no known lever left: its remaining difference is explained '
         '(`build.py audit` shows the same behaviour as the exe, or only different inlining decisions) and every '
         'README rule and tool has been tried (the notes say against which wave\'s rules). It stays in the build '
         '(compiled, checked, diffed); agents skip it until a new rule or tool arrives. To unpark one, delete '
         'the `// PARKED:` line in the comment block above its `// STUB:` line. The audit column\'s hints '
         '(mset, zero-reg, lazy-push) are explained in tools/audit.py.',
         '',
         'Columns: *aligned* = instruction mismatches after aligning our listing with the exe '
         '(`build.py diff -a <addr>`), then the same ignoring stack offsets; *bytes* = our size / the exe extent; '
         '*audit* = `build.py audit -v <addr>` summary. Sorted closest first (by mismatches ignoring stack offsets).',
         '',
         '%d functions, %d bytes of exe code.' % (len(rows), sum(x['exe'] or 0 for x in rows)),
         '',
         '| # | address | function | file | status | bytes | aligned | audit | reason |',
         '|---|---|---|---|---|---|---|---|---|']
    for k, x in enumerate(rows, 1):
        a, r = x['a'], x['r']
        L.append('| %d | `%08x` | %s | [%s:%d](src/%s#L%d) | %s | %d / %s | %s / %s | %s | %s |' % (
            k, a.va, _md(a.name or a.symbol.name), a.unit.rel, a.line, a.unit.rel, a.line, r.status, r.size,
            x['exe'] if x['exe'] is not None else '?', x['n'], x['ns'], _md(x['audit']), _md(a.parked or '')))
    L += ['', '## Notes per function', '',
          'The comment block above each STUB, as left by the agents that worked on it (what was tried, what '
          'remains), and the commands to start from.', '']
    for x in rows:
        a = x['a']
        L += ['### `%08x` %s' % (a.va, a.name or a.symbol.name), '',
              '`src/%s:%d`, %s, %d vs %s bytes, %s / %s aligned mismatches (%d vs %d instructions). Audit: %s.' % (
                  a.unit.rel, a.line, x['r'].status, x['r'].size, x['exe'], x['n'], x['ns'], x['li'], x['ri'],
                  x['audit']),
              '',
              '```',
              'python tools/build.py diff -a %08x' % a.va,
              'python tools/build.py audit -v %08x' % a.va,
              'python tools/inline_budget.py %08x --exe' % a.va,
              '```', '']
        if a.notes:
            L += ['> ' + (n if n else '') for n in a.notes] + ['']
    open(OUT, 'w', encoding='utf-8', newline='').write('\n'.join(L) + '\n')
    print('wrote %s: %d functions' % (OUT, len(rows)))
    return 0
